# Generated by Django 3.2.4 on 2021-06-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_alter_announcement_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.ManyToManyField(related_name='category', through='advert.AnnounCategory', to='advert.Category'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='media',
            field=models.FileField(blank=True, upload_to='pics'),
        ),
    ]
