# Generated by Django 3.2.4 on 2021-06-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0006_auto_20210608_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='media',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
