# Generated by Django 3.2.4 on 2021-06-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0007_alter_announcement_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='media',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
