# Generated by Django 3.2.4 on 2021-06-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0009_auto_20210610_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.ManyToManyField(related_name='category', through='advert.AnnounCategory', to='advert.Category'),
        ),
    ]
